NoteTakingApp/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace NoteTakingApp.ViewModels
{
    public class Login
    {
        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; } = string.Empty;
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; } = string.Empty;
        public bool RememberMe { get; set; }
    }
}

NoteTakingApp/ViewModels/Registration.cs
using System.ComponentModel.DataAnnotations;

namespace NoteTakingApp.ViewModels
{
    public class Registration
    {
        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; } = string.Empty;

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; } = string.Empty;

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; } = string.Empty;

        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Password confirmation failed")]
        public string ConfirmPassword { get; set; } = string.Empty;
    }
}

NoteTakingApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace NoteTakingApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

NoteTakingApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NoteTakingApp.Entities;
using NoteTakingApp.Model;
using NoteTakingApp.ViewModels;

namespace NoteTakingApp.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly NoteDbContext _dbContext;
        private readonly UserManager<User> _userManager;
        public PaginatedList<Note> Notes { get; set; } = new PaginatedList<Note>();

        public IndexModel(NoteDbContext dbContext, UserManager<User> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }

        public async Task OnGetAsync(int pageIndex = 1)
        {
            
            var currentUser = await _userManager.GetUserAsync(User);
            var notes = _dbContext.Notes.Where(n => n.UserId == currentUser.Id);

            if (notes.Any())
            {
                foreach (var note in notes)
                {
                    if(note.Description.Length > 100)
                    {
                        note.Description = note.Description[..97] + "...";
                    }
                    
                }
            }

            int pageSize = 12;

            Notes = await PaginatedList<Note>.CreateAsync(notes, pageSize, pageIndex);
        }

        public async Task<IActionResult> OnPostDeleteAsync(int noteId)
        {
            var note = await _dbContext.Notes.FirstOrDefaultAsync(n => n.Id == noteId);
            if (note != null)
            {
                _dbContext.Notes.Remove(note);
                await _dbContext.SaveChangesAsync();
            }

            return RedirectToPage("/Index");
        }
    }
}

NoteTakingApp/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NoteTakingApp.Entities;
using NoteTakingApp.ViewModels;

namespace NoteTakingApp.Pages
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<User> _signInManager;
        [BindProperty]
        public Login Model { get; set; }

        public LoginModel(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(string? returnUrl = null) 
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(Model.Name, Model.Password, Model.RememberMe, false);

                if(result.Succeeded)
                {
                    if(returnUrl == null || returnUrl == "/")
                    {
                        return RedirectToPage("Index");
                    }
                    else
                    {
                        return RedirectToPage(returnUrl);
                    }
                }

                ModelState.AddModelError("", "Username or password incorrect");
            }

            

            return Page();
        }
    }
}

NoteTakingApp/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NoteTakingApp.Entities;

namespace NoteTakingApp.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<User> _signInManager;
        public LogoutModel(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync() 
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }

        public IActionResult OnPostStay()
        {
            return RedirectToPage("Index");
        }
    }
}

NoteTakingApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NoteTakingApp.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

NoteTakingApp/Pages/Registration.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NoteTakingApp.Entities;
using NoteTakingApp.ViewModels;

namespace NoteTakingApp.Pages
{
    public class RegistrationModel : PageModel
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        [BindProperty]
        public Registration Model { get; set; } 
        public RegistrationModel(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = new User { UserName = Model.Name, Email = Model.Email };
                var result = await _userManager.CreateAsync(user, Model.Password);

                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToPage("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description); 
                }
            }

            return Page();
        }
    }
}

NoteTakingApp/Pages/Index.cshtml
@page 
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    int count = 1;
}

<div class="bg-secondary bg-opacity-10 py-2 mb-2">
    <div class="container d-flex align-items-center">
        <h1>Notes</h1>
        <a asp-page="/Notes/Add" class="btn btn-primary ms-3" style="font-size:14px">Add new</a>
    </div>
</div>

<div class="container">
    <table class="table table-hover border-dark align-middle">
        <thead>
            <tr>
                <td>#</td>
                <td>Title</td>
                <td>Description</td>
                <td></td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var note in Model.Notes)
            {
                <tr>
                    <td>@(count++)</td>
                    <td>@note.Title</td>
                    <td>@note.Description</td>
                    <td>
                        <a class="btn btn-sm btn-info" asp-page="/Notes/Update" asp-route-noteId="@note.Id">View</a>
                    </td>
                    <td>
                        <form method="post" asp-page-handler="Delete">
                            <input type="hidden" name="noteId" value="@note.Id" />
                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @{
        var prevDisabled = !Model.Notes.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.Notes.HasNextPage ? "disabled" : "";
    }

    <a asp-page="Index" asp-route-pageIndex="@(Model.Notes.PageIndex-1)" class="btn btn-primary @prevDisabled">Previous</a>
    <a asp-page="Index" asp-route-pageIndex="@(Model.Notes.PageIndex+1)" class="btn btn-primary @nextDisabled">Next</a>
</div>

NoteTakingApp/Pages/Login.cshtml
@page
@model NoteTakingApp.Pages.LoginModel
@{
}

<section class="vh-100">
    <div class="d-flex align-items-center h-100">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-5">Sign in</h2>

                            <form method="post">

                                <div asp-validation-summary="All" class="text-danger"></div>

                                <div class="mb-4">
                                    <input type="text" asp-for="Model.Name" placeholder="Your Username" class="form-control form-control-lg" />
                                    <span class="text-danger" asp-validation-for="Model.Name"></span>
                                </div>

                                <div class="mb-4">
                                    <input type="password" asp-for="Model.Password" placeholder="Password" class="form-control form-control-lg" />
                                    <span class="text-danger" asp-validation-for="Model.Password"></span>
                                </div>

                                <div class="mb-4 form-check d-flex justify-content-center">
                                    <input type="checkbox" asp-for="Model.RememberMe" class="form-check-input"/>
                                    <label class="form-check-label" asp-for="Model.RememberMe">Remember Me</label>
                                </div>

                                <div class="d-flex justify-content-center">
                                    <button type="submit"
                                            class="btn btn-success btn-block btn-lg text-body" style="background: linear-gradient(to right, rgba(132, 250, 176, 1), rgba(143, 211, 244, 1))">
                                        Login
                                    </button>
                                </div>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

NoteTakingApp/Pages/Logout.cshtml
@page
@model NoteTakingApp.Pages.LogoutModel
@{
}


<form method="post">
    <div class="container pt-5">
        <div class="mx-auto w-25 text-center fs-3">
            Are you sure you want to <strong>logout</strong>?
        </div>

        <div class="mx-auto w-25 mt-3 d-flex justify-content-between">
            <input type="submit" value="Yes" class="btn btn-primary btn-lg ms-3" asp-page-handler="Logout"/>
            <input type="submit" value="No" class="btn btn-light btn-lg border-dark me-3" asp-page-handler="Stay"/>
        </div>
    </div>
</form>

NoteTakingApp/Pages/Registration.cshtml
@page
@model NoteTakingApp.Pages.RegistrationModel
@{
    ViewData["Title"] = "Registration";
}

<section class="vh-100">
    <div class="d-flex align-items-center h-100">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-5">Create an account</h2>

                            <form method="post">

                                <div asp-validation-summary="All" class="text-danger"></div>

                                <div class="form-outline mb-4">
                                    <input type="text" asp-for="Model.Name" placeholder="Your Name" class="form-control form-control-lg" />
                                    <span class="text-danger" asp-validation-for="Model.Name"></span>
                                </div>

                                <div class="form-outline mb-4">
                                    <input type="email" asp-for="Model.Email" placeholder="Your Email" class="form-control form-control-lg" />
                                    <span class="text-danger" asp-validation-for="Model.Email"></span>
                                </div>

                                <div class="form-outline mb-4">
                                    <input type="password" asp-for="Model.Password" placeholder="Password" class="form-control form-control-lg" />
                                    <span class="text-danger" asp-validation-for="Model.Password"></span>
                                </div>

                                <div class="form-outline mb-4">
                                    <input type="password" asp-for="Model.ConfirmPassword" placeholder="Repeat your password" class="form-control form-control-lg" />
                                    <span class="text-danger" asp-validation-for="Model.ConfirmPassword"></span>
                                </div>

                                <div class="d-flex justify-content-center">
                                    <button type="submit"
                                            class="btn btn-success btn-block btn-lg text-body" style="background: linear-gradient(to right, rgba(132, 250, 176, 1), rgba(143, 211, 244, 1))">
                                        Register
                                    </button>
                                </div>

                                <p class="text-center text-muted mt-5 mb-0">
                                    Have already an account? <a asp-page="/Login" class="fw-bold text-body"><u>Login here</u></a>
                                </p>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>