NoteTakingApp/Entities/Note.cs
namespace NoteTakingApp.Entities
{
    public class Note
    {
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;

        public string UserId { get; set; }
        public User User { get; set; } = default!;
    }
}

NoteTakingApp/ViewModels/Add.cs
using System.ComponentModel.DataAnnotations;

namespace NoteTakingApp.ViewModels
{
    public class Add
    {
        public int NoteId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
    }
}

NoteTakingApp/Pages/Notes/Add.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NoteTakingApp.Entities;
using NoteTakingApp.Model;
using NoteTakingApp.ViewModels;
using System.ComponentModel.DataAnnotations;

namespace NoteTakingApp.Pages.Notes
{
    [Authorize]
    public class AddModel : PageModel
    {
        private readonly NoteDbContext _dbContext;
        private readonly UserManager<User> _userManager;

        [BindProperty]
        public Add Model { get; set; }

        public AddModel(NoteDbContext dbContext, UserManager<User> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostSaveAsync() 
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }

            var currentUser = await _userManager.GetUserAsync(User);

            var note = new Note
            {
                Title = Model.Title,
                Description = Model.Description,
                UserId = currentUser.Id,
                User = currentUser
            };

            await _dbContext.Notes.AddAsync(note);
            await _dbContext.SaveChangesAsync();
            return RedirectToPage("/Index");
        }

        public IActionResult OnPostDeleteAsync()
        {
            return RedirectToPage("/Index");
        }
    }
}

NoteTakingApp/Pages/Notes/Update.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NoteTakingApp.Model;
using NoteTakingApp.ViewModels;

namespace NoteTakingApp.Pages.Notes
{
    public class UpdateModel : PageModel
    {
        private readonly NoteDbContext _dbContext;
        [BindProperty]
        public Add Model { get; set; }
        public UpdateModel(NoteDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public async Task OnGet(int noteId)
        {
            Model = new Add
            {
                NoteId = noteId
            };

            var currentNote = await _dbContext.Notes.FirstOrDefaultAsync(n => n.Id == noteId);

            if(currentNote != null)
            {
                Model.Title = currentNote.Title;
                Model.Description = currentNote.Description;
            }
        }

        public async Task<IActionResult> OnPostUpdateAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var currentNote = await _dbContext.Notes.FirstOrDefaultAsync(n => n.Id == Model.NoteId);

            if(currentNote != null)
            {
                currentNote.Title = Model.Title;
                currentNote.Description = Model.Description;
                await _dbContext.SaveChangesAsync();
            }

            return RedirectToPage("/Index");
        }
    }
}

NoteTakingApp/Pages/Notes/Add.cshtml
@page
@model NoteTakingApp.Pages.Notes.AddModel
@{
}

<div class="container pt-5">
    <form method="post">
        <div class="row d-flex justify-content-center pt-5">
            <div class="col-6 p-5 border border-dark" style="border-radius: 15px">

                <div class="mb-3">
                    <label class="form-label h4" asp-for="Model.Title">Title</label>
                    <input type="text" class="form-control" placeholder="Your title" asp-for="Model.Title" />
                </div>

                <div class="mb-4">
                    <label class="form-label h4" asp-for="Model.Description">Description</label>
                    <textarea class="form-control" placeholder="Leave a comment here" asp-for="Model.Description" style="height: 150px"></textarea>
                </div>

                <div class="mb-3 d-flex justify-content-between">
                    <button type="submit" class="btn btn-lg btn-primary">Save</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>

            </div>

        </div>
        
    </form>
</div>

NoteTakingApp/Pages/Notes/Update.cshtml
@page
@model NoteTakingApp.Pages.Notes.UpdateModel
@{
}

<div class="container pt-5">
    <form method="post">
        <div class="row d-flex justify-content-center pt-5">
            <div class="col-6 p-5 border border-dark" style="border-radius: 15px">

                <div class="mb-3">
                    <label class="form-label h4" asp-for="Model.Title">Title</label>
                    <input type="text" class="form-control" placeholder="Your title" asp-for="Model.Title" value="@Model.Model.Title"/>
                    <span class="text-danger" asp-validation-for="Model.Title"></span>
                </div>

                <div class="mb-4">
                    <label class="form-label h4" asp-for="Model.Description">Description</label>
                    <textarea class="form-control" placeholder="Leave a comment here" asp-for="Model.Description" style="height: 150px">@Model.Model.Description</textarea>
                    <span class="text-danger" asp-validation-for="Model.Description"></span>
                </div>

                <div class="mb-3 d-flex justify-content-center">
                    <input type="hidden" asp-for="Model.NoteId"/>
                    <button type="submit" class="btn btn-lg btn-primary" asp-page-handler="Update">Update</button>
                </div>

            </div>

        </div>

    </form>
</div>